//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Session4Entities : DbContext
    {
        public Session4Entities()
            : base("name=Session4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Part> Parts { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TransactionType> TransactionTypes { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
    
        public virtual ObjectResult<AllActivities_Result> AllActivities()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AllActivities_Result>("AllActivities");
        }
    
        public virtual ObjectResult<SelectAllActivities_Result> SelectAllActivities()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectAllActivities_Result>("SelectAllActivities");
        }
    
        public virtual ObjectResult<All_Activities_Result> All_Activities()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<All_Activities_Result>("All_Activities");
        }
    }
}
